// English text keyed by the exact Turkish source. Prices and products remain in menu-data.js.
window.MENU_EN = {
  "Kahvaltı Tabağı": "Breakfast Plate",
  "2 Kişilik Kahvaltı": "Breakfast for Two",
  "3 Kişilik Kahvaltı": "Breakfast for Three",
  "Express Kahvaltı": "Express Breakfast",
  "Sporcu Kahvaltısı": "Athlete’s Breakfast",
  "Söğüş Tabağı": "Fresh Vegetable Plate",
  "Full Söğüş Tabağı": "Full Fresh Vegetable Plate",
  "Peynir Tabağı": "Cheese Plate",
  "Aperatif Sepeti": "Snack Basket",
  "Patates Kızartması": "French Fries",
  "Elma Dilim Patates": "Potato Wedges",
  "Sosis Kızartması": "Fried Sausages",
  "Kangal Sucuk Tava": "Pan-Fried Ring Sucuk (Turkish Sausage)",
  "Soslu Sosis": "Sausages in Sauce",
  "Haşlanmış Yumurta": "Boiled Egg",
  "Tahin Pekmez": "Tahini & Molasses",
  "Bal Kaymak": "Honey & Clotted Cream",
  "Yarım Bal Kaymak": "Honey & Clotted Cream (Half Portion)",
  "Sosluklar": "Small Sides",
  "Peynir Çeşitleri": "Choice of Cheese",
  "Jumbo 1.5 Porsiyon Menemen": "Jumbo Menemen (1.5 Portions)",
  "Sporcu 1.5 Porsiyon Menemen": "Athlete’s Menemen (1.5 Portions)",
  "Sporcu Yumurtası 1.5 Porsiyon": "Athlete’s Eggs (1.5 Portions)",
  "Sigara Böreği (6 adet)": "Crispy Pastry Rolls (6 Pieces)",
  "Ev Böreği (250 gr.)": "Homemade Börek Pastry (250 g)",
  "Coca Cola 330 ml": "Coca Cola 330 ml",
  "Coca Cola Zero 330 ml": "Coca Cola Zero 330 ml",
  "Capy (Şeftali, Vişne, Karışık)": "Capy Juice (Peach, Sour Cherry, Mixed Fruit)",
  "Lipton Ice Tea (Şeftali, Limon)": "Lipton Ice Tea (Peach, Lemon)",
  "Nescafe Express": "Nescafe Express",
  "Süt": "Milk",
  "Ballı Süt": "Milk with Honey",
  "Soda": "Sparkling Mineral Water",
  "Limonlu Soda": "Lemon Mineral Water",
  "Ayran": "Ayran (Yogurt Drink)",
  "Taze Sıkma Portakal Suyu 200 ml": "Freshly Squeezed Orange Juice 200 ml",
  "Taze Sıkma Portakal Suyu 330 ml": "Freshly Squeezed Orange Juice 330 ml",
  "Su": "Water",
  "Çay Bardak": "Tea (Glass)",
  "Çay Fincan": "Tea (Cup)",
  "Americano": "Americano",
  "Espresso": "Espresso",
  "Sade Menemen": "Plain Menemen (Turkish Scrambled Eggs)",
  "Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Kashar Cheese",
  "Beyaz Peynirli Menemen": "Menemen (Turkish Scrambled Eggs) with White Cheese",
  "Beyaz Peynirli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with White Cheese, Kashar Cheese",
  "Patatesli Menemen": "Menemen (Turkish Scrambled Eggs) with Potato",
  "Patatesli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Potato, Kashar Cheese",
  "Patatesli, Beyaz Peynirli Menemen": "Menemen (Turkish Scrambled Eggs) with Potato, White Cheese",
  "Patatesli, Sosisli Menemen": "Menemen (Turkish Scrambled Eggs) with Potato, Sausage",
  "Patatesli, Sosisli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Potato, Sausage, Kashar Cheese",
  "Sosisli Menemen": "Menemen (Turkish Scrambled Eggs) with Sausage",
  "Sosisli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Sausage, Kashar Cheese",
  "Sosisli, Beyaz Peynirli Menemen": "Menemen (Turkish Scrambled Eggs) with Sausage, White Cheese",
  "Sucuklu Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage)",
  "Sucuklu, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), Kashar Cheese",
  "Sucuklu, Beyaz Peynirli Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), White Cheese",
  "Sucuklu, Patatesli Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), Potato",
  "Sucuklu, Patatesli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), Potato, Kashar Cheese",
  "Sucuklu, Patatesli, Beyaz Peynirli Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), Potato, White Cheese",
  "Sucuklu, Patatesli, Sosisli Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), Potato, Sausage",
  "Sucuklu, Patatesli, Sosisli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Sucuk (Turkish Sausage), Potato, Sausage, Kashar Cheese",
  "Kavurmalı Menemen": "Menemen (Turkish Scrambled Eggs) with Kavurma (Slow-Cooked Meat)",
  "Kavurmalı, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Kavurma (Slow-Cooked Meat), Kashar Cheese",
  "Kavurmalı, Patatesli Menemen": "Menemen (Turkish Scrambled Eggs) with Kavurma (Slow-Cooked Meat), Potato",
  "Kavurmalı, Patatesli, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Kavurma (Slow-Cooked Meat), Potato, Kashar Cheese",
  "Kavurmalı, Patatesli, Beyaz Peynirli Menemen": "Menemen (Turkish Scrambled Eggs) with Kavurma (Slow-Cooked Meat), Potato, White Cheese",
  "Kangal Sucuklu Menemen": "Menemen (Turkish Scrambled Eggs) with Ring Sucuk (Turkish Sausage)",
  "Kangal Sucuklu, Kaşarlı Menemen": "Menemen (Turkish Scrambled Eggs) with Ring Sucuk (Turkish Sausage), Kashar Cheese",
  "Kangal Sucuklu, Kaşarlı, Patatesli Menemen": "Menemen (Turkish Scrambled Eggs) with Ring Sucuk (Turkish Sausage), Kashar Cheese, Potato",
  "Sade Yumurta": "Plain Eggs",
  "Kaşarlı Yumurta": "Eggs with Kashar Cheese",
  "Beyaz Peynirli Yumurta": "Eggs with White Cheese",
  "Beyaz Peynirli, Kaşarlı Yumurta": "Eggs with White Cheese, Kashar Cheese",
  "Sosisli Yumurta": "Eggs with Sausage",
  "Sosisli, Kaşarlı Yumurta": "Eggs with Sausage, Kashar Cheese",
  "Sosisli, Beyaz Peynirli Yumurta": "Eggs with Sausage, White Cheese",
  "Patatesli Yumurta": "Eggs with Potato",
  "Patatesli, Kaşarlı Yumurta": "Eggs with Potato, Kashar Cheese",
  "Patatesli, Beyaz Peynirli Yumurta": "Eggs with Potato, White Cheese",
  "Patatesli, Sosisli Yumurta": "Eggs with Potato, Sausage",
  "Patatesli, Sosisli, Kaşarlı Yumurta": "Eggs with Potato, Sausage, Kashar Cheese",
  "Sucuklu Yumurta": "Eggs with Sucuk (Turkish Sausage)",
  "Sucuklu, Kaşarlı Yumurta": "Eggs with Sucuk (Turkish Sausage), Kashar Cheese",
  "Sucuklu, Beyaz Peynirli Yumurta": "Eggs with Sucuk (Turkish Sausage), White Cheese",
  "Sucuklu, Patatesli Yumurta": "Eggs with Sucuk (Turkish Sausage), Potato",
  "Sucuklu, Patatesli, Kaşarlı Yumurta": "Eggs with Sucuk (Turkish Sausage), Potato, Kashar Cheese",
  "Sucuklu, Patatesli, Beyaz Peynirli Yumurta": "Eggs with Sucuk (Turkish Sausage), Potato, White Cheese",
  "Sucuklu, Patatesli, Sosisli Yumurta": "Eggs with Sucuk (Turkish Sausage), Potato, Sausage",
  "Sucuklu, Patatesli, Sosisli, Kaşarlı Yumurta": "Eggs with Sucuk (Turkish Sausage), Potato, Sausage, Kashar Cheese",
  "Kavurmalı Yumurta": "Eggs with Kavurma (Slow-Cooked Meat)",
  "Kavurmalı, Kaşarlı Yumurta": "Eggs with Kavurma (Slow-Cooked Meat), Kashar Cheese",
  "Kavurmalı, Patatesli Yumurta": "Eggs with Kavurma (Slow-Cooked Meat), Potato",
  "Kavurmalı, Patatesli, Kaşarlı Yumurta": "Eggs with Kavurma (Slow-Cooked Meat), Potato, Kashar Cheese",
  "Kangal Sucuklu Yumurta": "Eggs with Ring Sucuk (Turkish Sausage)",
  "Kangal Sucuklu, Beyaz Peynirli Yumurta": "Eggs with Ring Sucuk (Turkish Sausage), White Cheese",
  "Kangal Sucuklu, Kaşarlı Yumurta": "Eggs with Ring Sucuk (Turkish Sausage), Kashar Cheese",
  "Kangal Sucuklu, Patatesli Yumurta": "Eggs with Ring Sucuk (Turkish Sausage), Potato",
  "Kangal Sucuklu, Patatesli, Kaşarlı Yumurta": "Eggs with Ring Sucuk (Turkish Sausage), Potato, Kashar Cheese",
  "Sade Omlet": "Plain Omelette",
  "Kaşarlı Omlet": "Omelette with Kashar Cheese",
  "Beyaz Peynirli Omlet": "Omelette with White Cheese",
  "Sucuklu Omlet": "Omelette with Sucuk (Turkish Sausage)",
  "Sucuklu, Kaşarlı Omlet": "Omelette with Sucuk (Turkish Sausage), Kashar Cheese",
  "Sucuklu, Beyaz Peynirli Omlet": "Omelette with Sucuk (Turkish Sausage), White Cheese",
  "Patatesli Omlet": "Omelette with Potato",
  "Patatesli, Kaşarlı Omlet": "Omelette with Potato, Kashar Cheese",
  "Patatesli, Sucuklu Omlet": "Omelette with Potato, Sucuk (Turkish Sausage)",
  "Patatesli, Sucuklu, Kaşarlı Omlet": "Omelette with Potato, Sucuk (Turkish Sausage), Kashar Cheese",
  "Patatesli, Beyaz Peynirli Omlet": "Omelette with Potato, White Cheese",
  "Sosisli Omlet": "Omelette with Sausage",
  "Sosisli, Kaşarlı Omlet": "Omelette with Sausage, Kashar Cheese",
  "Sosisli, Beyaz Peynirli Omlet": "Omelette with Sausage, White Cheese",
  "Sosisli, Patatesli Omlet": "Omelette with Sausage, Potato",
  "Sosisli, Patatesli, Kaşarlı Omlet": "Omelette with Sausage, Potato, Kashar Cheese",
  "Sosisli, Sucuklu Omlet": "Omelette with Sausage, Sucuk (Turkish Sausage)",
  "Sosisli, Sucuklu, Kaşarlı Omlet": "Omelette with Sausage, Sucuk (Turkish Sausage), Kashar Cheese",
  "Sebzeli Omlet": "Vegetable Omelette",
  "Kavurmalı Omlet": "Omelette with Kavurma (Slow-Cooked Meat)",
  "Kavurmalı, Kaşarlı Omlet": "Omelette with Kavurma (Slow-Cooked Meat), Kashar Cheese",
  "Kavurmalı, Patatesli Omlet": "Omelette with Kavurma (Slow-Cooked Meat), Potato",
  "Kavurmalı, Patatesli, Kaşarlı Omlet": "Omelette with Kavurma (Slow-Cooked Meat), Potato, Kashar Cheese",
  "Kangal Sucuklu Omlet": "Omelette with Ring Sucuk (Turkish Sausage)",
  "Kangal Sucuklu, Kaşarlı Omlet": "Omelette with Ring Sucuk (Turkish Sausage), Kashar Cheese",
  "Kangal Sucuklu, Beyaz Peynirli Omlet": "Omelette with Ring Sucuk (Turkish Sausage), White Cheese",
  "Kangal Sucuklu, Patatesli Omlet": "Omelette with Ring Sucuk (Turkish Sausage), Potato",
  "Kangal Sucuklu, Patatesli, Kaşarlı Omlet": "Omelette with Ring Sucuk (Turkish Sausage), Potato, Kashar Cheese",
  "Mantarlı Omlet": "Omelette with Mushroom",
  "Mantarlı, Kaşarlı Omlet": "Omelette with Mushroom, Kashar Cheese",
  "Mantarlı, Beyaz Peynirli Omlet": "Omelette with Mushroom, White Cheese",
  "Mantarlı, Patatesli Omlet": "Omelette with Mushroom, Potato",
  "Mantarlı, Patatesli, Kaşarlı Omlet": "Omelette with Mushroom, Potato, Kashar Cheese",
  "Mantarlı, Sucuklu Omlet": "Omelette with Mushroom, Sucuk (Turkish Sausage)",
  "Mantarlı, Sucuklu, Kaşarlı Omlet": "Omelette with Mushroom, Sucuk (Turkish Sausage), Kashar Cheese",
  "Mantarlı, Sosisli Omlet": "Omelette with Mushroom, Sausage",
  "Mantarlı, Sosisli, Kaşarlı Omlet": "Omelette with Mushroom, Sausage, Kashar Cheese",
  "Vejeteryan Omlet": "Vegetarian Omelette",
  "Ispanaklı Gözleme": "Gözleme (Stuffed Flatbread) with Spinach",
  "Ispanaklı, Beyaz Peynirli Gözleme": "Gözleme (Stuffed Flatbread) with Spinach, White Cheese",
  "Ispanaklı, Kaşarlı Gözleme": "Gözleme (Stuffed Flatbread) with Spinach, Kashar Cheese",
  "Kaşarlı Gözleme": "Gözleme (Stuffed Flatbread) with Kashar Cheese",
  "Beyaz Peynirli Gözleme": "Gözleme (Stuffed Flatbread) with White Cheese",
  "Sucuklu Gözleme": "Gözleme (Stuffed Flatbread) with Sucuk (Turkish Sausage)",
  "Sucuklu, Kaşarlı Gözleme": "Gözleme (Stuffed Flatbread) with Sucuk (Turkish Sausage), Kashar Cheese",
  "Patatesli Gözleme": "Gözleme (Stuffed Flatbread) with Potato",
  "Patatesli, Kaşarlı Gözleme": "Gözleme (Stuffed Flatbread) with Potato, Kashar Cheese",
  "Patatesli, Beyaz Peynirli Gözleme": "Gözleme (Stuffed Flatbread) with Potato, White Cheese",
  "Kavurmalı Gözleme": "Gözleme (Stuffed Flatbread) with Kavurma (Slow-Cooked Meat)",
  "Kavurmalı, Kaşarlı Gözleme": "Gözleme (Stuffed Flatbread) with Kavurma (Slow-Cooked Meat), Kashar Cheese",
  "Kavurmalı, Beyaz Peynirli Gözleme": "Gözleme (Stuffed Flatbread) with Kavurma (Slow-Cooked Meat), White Cheese",
  "Sade Pişi (3 adet)": "Plain Pişi (Fried Dough) (3 Pieces)",
  "Sade Pişi (1 adet)": "Plain Pişi (Fried Dough) (1 Piece)",
  "Fındık Kremalı Pişi (3 adet)": "Pişi (Fried Dough) with Hazelnut Cream (3 Pieces)",
  "Fındık Kremalı Pişi (1 adet)": "Pişi (Fried Dough) with Hazelnut Cream (1 Piece)",
  "Kaşarlı Pişi (3 adet)": "Pişi (Fried Dough) with Kashar Cheese (3 Pieces)",
  "Kaşarlı Pişi (1 adet)": "Pişi (Fried Dough) with Kashar Cheese (1 Piece)",
  "Lor Peynirli Pişi (3 adet)": "Pişi (Fried Dough) with Curd Cheese (3 Pieces)",
  "Lor Peynirli Pişi (1 adet)": "Pişi (Fried Dough) with Curd Cheese (1 Piece)",
  "Patatesli Pişi (3 adet)": "Pişi (Fried Dough) with Potato (3 Pieces)",
  "Patatesli Pişi (1 adet)": "Pişi (Fried Dough) with Potato (1 Piece)",
  "Kahvaltı": "Breakfast",
  "Kahvaltılıklar": "Breakfast Sides",
  "Menemen": "Menemen",
  "Yumurta": "Eggs",
  "Omlet": "Omelettes",
  "Gözleme": "Gözleme",
  "Börek & Pişi": "Pastries & Fried Dough",
  "Soğuk İçecekler": "Cold Drinks",
  "Sıcak İçecekler": "Hot Drinks",
  "Fiyatlarımıza KDV dahildir.": "Prices include VAT.",
  "Beyaz peynir, taze kaşar, tel peynir, zeytin, salam, sosis ( 2 adet ), patates kızartması, sigara böreği, haşlanmış yumurta, kakaolu fındık kreması, acı ezme, reçel, tereyağı, bal, kokteyl domates, salatalık, biber + 2 adet çay": "White cheese, fresh kashar cheese, string cheese, olives, salami, sausages (2 pieces), French fries, crispy pastry rolls, boiled egg, cocoa hazelnut spread, spicy tomato dip, jam, butter, honey, cocktail tomatoes, cucumber, pepper + 2 teas",
  "Beyaz peynir, taze kaşar, tel peynir, örgü peynir, ev yapımı tepsi böreği, zeytin, salam, sosis (4 adet), patates kızartması, sigara böreği, haşlanmış yumurta, kakaolu fındık kreması, acı ezme, reçel, tereyağı, bal, kokteyl domates, salatalık, biber + 4 adet çay": "White cheese, fresh kashar cheese, string cheese, braided cheese, homemade tray-baked börek pastry, olives, salami, sausages (4 pieces), French fries, crispy pastry rolls, boiled egg, cocoa hazelnut spread, spicy tomato dip, jam, butter, honey, cocktail tomatoes, cucumber, pepper + 4 teas",
  "Beyaz peynir, taze kaşar, tel peynir, örgü peynir, ev yapımı tepsi böreği, zeytin, salam, sosis (6 adet), patates kızartması, sigara böreği, haşlanmış yumurta, ev yapımı tepsi böreği, acı ezme, reçel, tereyağı, bal, kokteyl domates, salatalık, biber + 6 adet çay": "White cheese, fresh kashar cheese, string cheese, braided cheese, homemade tray-baked börek pastry, olives, salami, sausages (6 pieces), French fries, crispy pastry rolls, boiled egg, homemade tray-baked börek pastry, spicy tomato dip, jam, butter, honey, cocktail tomatoes, cucumber, pepper + 6 teas",
  "Beyaz peynir, taze kaşar, zeytin, sigara böreği, patates kızartması, reçel, domates, salatalık + 1 adet çay": "White cheese, fresh kashar cheese, olives, crispy pastry rolls, French fries, jam, tomato, cucumber + 1 tea",
  "Beyaz peynir, tel peynir, örgü peynir, 3 adet haşlanmış yumurta, zeytin, tahin-pekmez, domates, salatalık, biber, roka, maydanoz + 2 adet çay veya 1 adet sade kahve": "White cheese, string cheese, braided cheese, 3 boiled eggs, olives, tahini and molasses, tomato, cucumber, pepper, rocket, parsley + 2 teas or 1 black coffee",
  "Domates, salatalık, biber ": "Tomato, cucumber, pepper",
  "Domates, salatalık, biber, beyaz peynir, zeytin": "Tomato, cucumber, pepper, white cheese, olives",
  "Beyaz peynir, kaşar, tel peynir, örgü peynir": "White cheese, kashar cheese, string cheese, braided cheese",
  "Elma dilim patates, parmak patates, sosis, sigara böreği": "Potato wedges, French fries, sausages, crispy pastry rolls",
  "Bal, acı ezme, zeytin, tereyağ, kaymak, kakaolu fındık kreması (45-50 Gr.)": "Honey, spicy tomato dip, olives, butter, clotted cream, cocoa hazelnut spread (45–50 g)",
  "Beyaz peynir, kaşar, tel peynir, örgü peynir (Seçeceğiniz tek bir çeşit porsiyon olarak servis edilir)": "White cheese, kashar cheese, string cheese, braided cheese (One variety of your choice is served as a portion)",
  "3 yumurta, piliç sosis, piliç sucuk, beyaz peynir, kaşar peyniri.": "3 eggs, chicken sausage, chicken sucuk, white cheese, kashar cheese.",
  "2 adet yumurta sarısı, 5 adet yumurta beyazı, piliç sucuk, patates, beyaz peynir.": "2 egg yolks, 5 egg whites, chicken sucuk, potato, white cheese."
};
